// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjnxycgbnvovucrulrpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbnh5Y2dibnZvdnVjcnVscnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Mjk1NDEsImV4cCI6MjA2NjIwNTU0MX0.4H3Tr85MgPsDqbMiLr65snb7j8QkfmlYsxIU2u9yNcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);